### ISSUE TITLE
location of repo on file-system

### ISSUE THREAD

**Issue by MareoRaft** [ghseeli/dotfiles#1]
When cloning this repo for use, is it required to be in a certain location on the file-system?  I saw the line

    # User configuration

    . $HOME/dotfiles/path/add_paths.sh

in .zshrc which seems to suggest that one should always keep this repo in their home directory.  (P.S. i am planning on installing this on my system soon so if there is anything i should know, LMK) (P.P.S. this project is really awesome)

**Comment by ghseeli** [comment]
Yes, clone the repo into you home directory. I'm glad you like it.
